#include "beremiz.h"
#ifndef __POUS_H
#define __POUS_H

#include "accessor.h"
#include "iec_std_lib.h"

__DECLARE_ENUMERATED_TYPE(LOGLEVEL,
  LOGLEVEL__CRITICAL,
  LOGLEVEL__WARNING,
  LOGLEVEL__INFO,
  LOGLEVEL__DEBUG
)
// FUNCTION_BLOCK LOGGER
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(BOOL,TRIG)
  __DECLARE_VAR(STRING,MSG)
  __DECLARE_VAR(LOGLEVEL,LEVEL)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(BOOL,TRIG0)

} LOGGER;

void LOGGER_init__(LOGGER *data__, BOOL retain);
// Code part
void LOGGER_body__(LOGGER *data__);
// FUNCTION_BLOCK PYTHON_EVAL
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(BOOL,TRIG)
  __DECLARE_VAR(STRING,CODE)
  __DECLARE_VAR(BOOL,ACK)
  __DECLARE_VAR(STRING,RESULT)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(DWORD,STATE)
  __DECLARE_VAR(STRING,BUFFER)
  __DECLARE_VAR(STRING,PREBUFFER)
  __DECLARE_VAR(BOOL,TRIGM1)
  __DECLARE_VAR(BOOL,TRIGGED)

} PYTHON_EVAL;

void PYTHON_EVAL_init__(PYTHON_EVAL *data__, BOOL retain);
// Code part
void PYTHON_EVAL_body__(PYTHON_EVAL *data__);
// FUNCTION_BLOCK PYTHON_POLL
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(BOOL,TRIG)
  __DECLARE_VAR(STRING,CODE)
  __DECLARE_VAR(BOOL,ACK)
  __DECLARE_VAR(STRING,RESULT)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(DWORD,STATE)
  __DECLARE_VAR(STRING,BUFFER)
  __DECLARE_VAR(STRING,PREBUFFER)
  __DECLARE_VAR(BOOL,TRIGM1)
  __DECLARE_VAR(BOOL,TRIGGED)

} PYTHON_POLL;

void PYTHON_POLL_init__(PYTHON_POLL *data__, BOOL retain);
// Code part
void PYTHON_POLL_body__(PYTHON_POLL *data__);
// FUNCTION_BLOCK PYTHON_GEAR
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(UINT,N)
  __DECLARE_VAR(BOOL,TRIG)
  __DECLARE_VAR(STRING,CODE)
  __DECLARE_VAR(BOOL,ACK)
  __DECLARE_VAR(STRING,RESULT)

  // FB private variables - TEMP, private and located variables
  PYTHON_EVAL PY_EVAL;
  __DECLARE_VAR(UINT,COUNTER)
  __DECLARE_VAR(UINT,_TMP_ADD10_OUT)
  __DECLARE_VAR(BOOL,_TMP_EQ13_OUT)
  __DECLARE_VAR(UINT,_TMP_SEL15_OUT)
  __DECLARE_VAR(BOOL,_TMP_AND7_OUT)

} PYTHON_GEAR;

void PYTHON_GEAR_init__(PYTHON_GEAR *data__, BOOL retain);
// Code part
void PYTHON_GEAR_body__(PYTHON_GEAR *data__);
// PROGRAM BIGPROJV1
// Data part
typedef struct {
  // PROGRAM Interface - IN, OUT, IN_OUT variables

  // PROGRAM private variables - TEMP, private and located variables
  __DECLARE_VAR(BOOL,FACTORYIORESET)
  __DECLARE_VAR(BOOL,ESTOP)
  __DECLARE_VAR(BOOL,STARTBUTTON)
  __DECLARE_VAR(BOOL,VIS0_BOOL0)
  __DECLARE_VAR(BOOL,VIS0_BOOL1)
  __DECLARE_VAR(BOOL,VIS0_BOOL2)
  __DECLARE_VAR(BOOL,VIS0_BOOL3)
  __DECLARE_VAR(BOOL,DIFF0)
  __DECLARE_VAR(BOOL,MC0_OPENED)
  __DECLARE_VAR(BOOL,MC1_OPENED)
  __DECLARE_VAR(BOOL,MC2_OPENED)
  __DECLARE_VAR(BOOL,MC0_BUSY)
  __DECLARE_VAR(BOOL,MC1_BUSY)
  __DECLARE_VAR(BOOL,MC2_BUSY)
  __DECLARE_VAR(BOOL,MC0_HASERROR)
  __DECLARE_VAR(BOOL,MC1_HASERROR)
  __DECLARE_VAR(BOOL,MC2_HASERROR)
  __DECLARE_VAR(BOOL,SELECTOR0_STATE0_OFF)
  __DECLARE_VAR(BOOL,SELECTOR0_STATE1_ON)
  __DECLARE_VAR(BOOL,RETRO0)
  __DECLARE_VAR(BOOL,RETRO1)
  __DECLARE_VAR(BOOL,RETRO2)
  __DECLARE_VAR(BOOL,RETRO3)
  __DECLARE_VAR(BOOL,RETRO4)
  __DECLARE_VAR(BOOL,DIFFUSE_3)
  __DECLARE_VAR(BOOL,DIFFUSE_4)
  __DECLARE_VAR(BOOL,DIFFUSE_5)
  __DECLARE_VAR(BOOL,VIS1_BOOL0)
  __DECLARE_VAR(BOOL,VIS1_BOOL1)
  __DECLARE_VAR(BOOL,VIS1_BOOL2)
  __DECLARE_VAR(BOOL,VIS1_BOOL3)
  __DECLARE_VAR(BOOL,VIS2_BOOL0)
  __DECLARE_VAR(BOOL,VIS2_BOOL1)
  __DECLARE_VAR(BOOL,VIS2_BOOL2)
  __DECLARE_VAR(BOOL,VIS2_BOOL3)
  __DECLARE_VAR(BOOL,DIFF1)
  __DECLARE_VAR(BOOL,DIFF2)
  __DECLARE_VAR(BOOL,PNP0_DETECT)
  __DECLARE_VAR(BOOL,PNP0_XMOVE)
  __DECLARE_VAR(BOOL,PNP0_ZMOVE)
  __DECLARE_VAR(BOOL,PNP0_ROTATING)
  __DECLARE_VAR(BOOL,PNP1_DETECT)
  __DECLARE_VAR(BOOL,PNP1_XMOVE)
  __DECLARE_VAR(BOOL,PNP1_ZMOVE)
  __DECLARE_VAR(BOOL,PNP1_ROTATING)
  __DECLARE_VAR(BOOL,PNP2_DETECT)
  __DECLARE_VAR(BOOL,PNP2_XMOVE)
  __DECLARE_VAR(BOOL,PNP2_ZMOVE)
  __DECLARE_VAR(BOOL,PNP2_ROTATING)
  __DECLARE_VAR(BOOL,PNP0_GRIPPER_ROTATE)
  __DECLARE_VAR(BOOL,PNP1_GRIPPER_ROTATE)
  __DECLARE_VAR(BOOL,PNP2_GRIPPER_ROTATE)
  __DECLARE_VAR(BOOL,BACK_LIM_PUSHER0)
  __DECLARE_VAR(BOOL,BACK_LIM_PUSHER1)
  __DECLARE_VAR(BOOL,BACK_LIM_PUSHER2)
  __DECLARE_VAR(BOOL,FRONT_LIM_PUSHER0)
  __DECLARE_VAR(BOOL,FRONT_LIM_PUSHER1)
  __DECLARE_VAR(BOOL,FRONT_LIM_PUSHER2)
  __DECLARE_VAR(BOOL,RETRO8)
  __DECLARE_VAR(BOOL,RETRO5)
  __DECLARE_VAR(BOOL,DIFFUSE_6)
  __DECLARE_VAR(BOOL,CONV_2M_0)
  __DECLARE_VAR(BOOL,CONV_2M_1)
  __DECLARE_VAR(BOOL,CONV_2M_2)
  __DECLARE_VAR(BOOL,CONV_2M_3)
  __DECLARE_VAR(BOOL,CONV_2M_4)
  __DECLARE_VAR(BOOL,CONV_2M_5)
  __DECLARE_VAR(BOOL,CONV_4M_0)
  __DECLARE_VAR(BOOL,CONV_4M_2)
  __DECLARE_VAR(BOOL,CONV_4M_4)
  __DECLARE_VAR(BOOL,CONV_4M_5)
  __DECLARE_VAR(BOOL,CURVED_CONV0_CW)
  __DECLARE_VAR(BOOL,CURVED_CONV1_CW)
  __DECLARE_VAR(BOOL,CURVED_CONV2_CCW)
  __DECLARE_VAR(BOOL,STOP_MC0)
  __DECLARE_VAR(BOOL,STOP_MC1)
  __DECLARE_VAR(BOOL,STOP_MC2)
  __DECLARE_VAR(BOOL,RESET_MC0)
  __DECLARE_VAR(BOOL,RESET_MC1)
  __DECLARE_VAR(BOOL,RESET_MC2)
  __DECLARE_VAR(BOOL,START_MC0)
  __DECLARE_VAR(BOOL,START_MC1)
  __DECLARE_VAR(BOOL,START_MC2)
  __DECLARE_VAR(BOOL,PIV_ARM0_TURN)
  __DECLARE_VAR(BOOL,PIV_ARM1_TURN)
  __DECLARE_VAR(BOOL,PIV_ARM0_BELT_PLUS)
  __DECLARE_VAR(BOOL,PIV_ARM1_BELT_PLUS)
  __DECLARE_VAR(BOOL,PIV_ARM0_BELT_MINUS)
  __DECLARE_VAR(BOOL,PIV_ARM1_BELT_MINUS)
  __DECLARE_VAR(BOOL,PUSHER0)
  __DECLARE_VAR(BOOL,PUSHER1)
  __DECLARE_VAR(BOOL,PUSHER2)
  __DECLARE_VAR(BOOL,SPUR_CONV0_PLUS)
  __DECLARE_VAR(BOOL,SPUR_CONV1_PLUS)
  __DECLARE_VAR(BOOL,SPUR_CONV0_MINUS)
  __DECLARE_VAR(BOOL,SPUR_CONV1_MINUS)
  __DECLARE_VAR(BOOL,PNP0_X)
  __DECLARE_VAR(BOOL,PNP1_X)
  __DECLARE_VAR(BOOL,PNP2_X)
  __DECLARE_VAR(BOOL,PNP0_Z)
  __DECLARE_VAR(BOOL,PNP1_Z)
  __DECLARE_VAR(BOOL,PNP2_Z)
  __DECLARE_VAR(BOOL,PNP0_GRAB)
  __DECLARE_VAR(BOOL,PNP1_GRAB)
  __DECLARE_VAR(BOOL,PNP2_GRAB)
  __DECLARE_VAR(BOOL,PNP0_ROT_CW)
  __DECLARE_VAR(BOOL,PNP1_ROT_CW)
  __DECLARE_VAR(BOOL,PNP2_ROT_CW)
  __DECLARE_VAR(BOOL,PNP0_GRIPPER_CW)
  __DECLARE_VAR(BOOL,PNP1_GRIPPER_CW)
  __DECLARE_VAR(BOOL,PNP2_GRIPPER_CW)
  __DECLARE_VAR(BOOL,PNP0_ROT_CCW)
  __DECLARE_VAR(BOOL,PNP1_ROT_CCW)
  __DECLARE_VAR(BOOL,PNP2_ROT_CCW)
  __DECLARE_VAR(BOOL,PNP0_GRIPPER_CCW)
  __DECLARE_VAR(BOOL,PNP1_GRIPPER_CCW)
  __DECLARE_VAR(BOOL,PNP2_GRIPPER_CCW)
  __DECLARE_VAR(BOOL,STARTBUTTONLIGHT)
  __DECLARE_VAR(BOOL,CONV_2M_6)
  __DECLARE_VAR(BOOL,BLUE_LIGHT)
  __DECLARE_VAR(BOOL,GREEN_LIGHT)
  __DECLARE_VAR(BOOL,YELLOW_LIGHT)
  __DECLARE_VAR(BOOL,STOPBLADE0)
  __DECLARE_VAR(BOOL,STOPBLADE1)
  __DECLARE_VAR(BOOL,STOPBLADE2)
  __DECLARE_VAR(BOOL,CONV_2M_7)
  __DECLARE_VAR(INT,DIGITAL_DISP0)
  __DECLARE_VAR(INT,DIGITAL_DISP1)
  __DECLARE_VAR(INT,DIGITAL_DISP2)
  RS RS0;
  RS RS1;
  __DECLARE_VAR(INT,PRESETVALUE_99)
  __DECLARE_VAR(BOOL,FACTORY_RESET)
  __DECLARE_VAR(BOOL,PNP1_LINE_RESET)
  __DECLARE_VAR(BOOL,MC_MAX_0)
  __DECLARE_VAR(BOOL,RAWGREEN_V0)
  __DECLARE_VAR(BOOL,BADGREEN_V0)
  __DECLARE_VAR(BOOL,RAWMETAL_V0)
  __DECLARE_VAR(BOOL,BADMETAL_V0)
  __DECLARE_VAR(BOOL,RAWBLUE_V0)
  __DECLARE_VAR(BOOL,BADBLUE_V0)
  __DECLARE_VAR(BOOL,BADMETAL_V2)
  __DECLARE_VAR(BOOL,RAWMETAL_V2)
  __DECLARE_VAR(BOOL,RAWBLUE_V1)
  __DECLARE_VAR(BOOL,BADBLUE_V1)
  __DECLARE_VAR(BOOL,GOOD_BLUE)
  __DECLARE_VAR(BOOL,GOOD_GREEN)
  __DECLARE_VAR(BOOL,GOOD_METAL)
  __DECLARE_VAR(BOOL,BAD_BLUE)
  __DECLARE_VAR(BOOL,BAD_GREEN)
  __DECLARE_VAR(BOOL,BAD_METAL)
  __DECLARE_VAR(INT,BAD_BLUE_CNT)
  __DECLARE_VAR(INT,GOOD_BLUE_CNT)
  RS RS2;
  RS RS3;
  RS RS4;
  RS RS6;
  RS RS7;
  RS RS5;
  RS RS8;
  RS RS9;
  RS RS10;
  RS RS11;
  RS RS13;
  RS RS12;
  RS RS14;
  RS RS15;
  RS RS16;
  __DECLARE_VAR(BOOL,L_D)
  RS RS17;
  RS RS18;
  RS RS19;
  __DECLARE_VAR(TIME,VARTIME1)
  __DECLARE_VAR(TIME,VARTIME2)
  __DECLARE_VAR(TIME,VARTIME3)
  __DECLARE_VAR(TIME,VARTIME4)
  __DECLARE_VAR(TIME,VARTIME5)
  __DECLARE_VAR(TIME,VARTIME6)
  __DECLARE_VAR(TIME,VARTIME7)
  __DECLARE_VAR(BOOL,PNPHASITEM)
  RS RS25;
  RS RS27;
  CTU CTU0;
  TON TON3;
  TON TON5;
  RS RS26;
  RS RS28;
  RS RS29;
  RS RS38;
  CTU CTU1;
  CTU CTU2;
  TON TON0;
  R_TRIG R_TRIG1;
  F_TRIG F_TRIG1;
  R_TRIG R_TRIG2;
  R_TRIG R_TRIG3;
  R_TRIG R_TRIG4;
  R_TRIG R_TRIG5;
  F_TRIG F_TRIG2;
  R_TRIG R_TRIG6;
  R_TRIG R_TRIG7;
  R_TRIG R_TRIG8;
  F_TRIG F_TRIG3;
  F_TRIG F_TRIG4;
  R_TRIG R_TRIG9;
  F_TRIG F_TRIG5;
  F_TRIG F_TRIG6;
  F_TRIG F_TRIG7;
  F_TRIG F_TRIG8;
  R_TRIG R_TRIG10;
  R_TRIG R_TRIG11;
  R_TRIG R_TRIG12;
  R_TRIG R_TRIG13;

} BIGPROJV1;

void BIGPROJV1_init__(BIGPROJV1 *data__, BOOL retain);
// Code part
void BIGPROJV1_body__(BIGPROJV1 *data__);
#endif //__POUS_H
